// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szinkron_Api.Data;

#nullable disable

namespace Szinkron_Api.Migrations
{
    [DbContext(typeof(Szinkron_ApiContext))]
    partial class Szinkron_ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("Szinkron_Api.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("filmaz");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cim");

                    b.Property<string>("Eredeti")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eredeti");

                    b.Property<int>("Ev")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ev");

                    b.Property<string>("MagyarSzoveg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("magyarszoveg");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rendezo");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("studio");

                    b.Property<string>("SzinkronRendezo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("szinkronrendezo");

                    b.HasKey("Id");

                    b.ToTable("film");
                });

            modelBuilder.Entity("Szinkron_Api.Models.Szinkron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("szinkid");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("filmaz");

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hang");

                    b.Property<string>("Szerep")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("szerep");

                    b.Property<string>("Szinesz")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("szinesz");

                    b.HasKey("Id");

                    b.ToTable("szinkron");
                });
#pragma warning restore 612, 618
        }
    }
}
